name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: 2bbb/of-actions/.github/workflows/build-addon.yml@main
    with:
      of_version: "0.12.0"
      addon_name: "ofxNozzle"
      test_app: "testApp"
      preprocessor_defines: "NOZZLE_PLATFORM_WINDOWS=1;NOZZLE_HAS_D3D11=1;NOZZLE_HAS_OPENGL=1"
      cache_key_suffix: "v10"
